### PR TITLE
Yousef feature

### PR DESCRIPTION
**Pull request by ysaleh23**
I have done the following tasks:

Created US feature file, created step definitions, and the pages file.

### CODE REVIEW

**Review by orick14 — APPROVED** [review]
Looks slick

**Comment by stevenclarkwoods44** [comment]
look clean!

**Comment by handesguven** [comment]
Looks clear!

**Review by handesguven — APPROVED** [review]
Looks clear!

**Review by stevenclarkwoods44 — APPROVED** [review]
I finally figured it out!

**Pull request merged**
